user:
  jwt:
    access:
      expire-seconds: ${USER_JWT_ACCESS_EXPIRE_SECONDS:3600}
      secret: ${USER_JWT_ACCESS_SECRET:secret}
    refresh:
      expire-seconds: ${USER_JWT_REFRESH_EXPIRE_SECONDS:604800}
      secret: ${USER_JWT_REFRESH_SECRET:secret}
