oidc:
  clients:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}
  providers:
    kakao:
      token-url: ${KAKAO_TOKEN_URI}
      token-info-url: ${KAKAO_USER_INFO_URI}
