oidc:
  clients:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/login/oauth2/code/KAKAO}
  providers:
    kakao:
      base-url: https://kauth.kakao.com
      token-endpoint: /oauth/token
      token-info-endpoint: /oauth/tokeninfo

logging:
  level:
    com.waterfogsw.glucose.user.infrastructure.client: DEBUG
